CREATE TABLE career_sites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  canonical_base_url TEXT NOT NULL,
  host TEXT NOT NULL,
  provider TEXT NOT NULL,
  display_name TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  successful_interval_seconds BIGINT NOT NULL DEFAULT 21600,
  CONSTRAINT uq_career_sites_host UNIQUE (host),
  CONSTRAINT ck_career_sites_url_https CHECK (canonical_base_url LIKE 'https://%'),
  CONSTRAINT ck_career_sites_provider CHECK (provider IN ('FLEX', 'GREETING', 'NINEHIRE')),
  CONSTRAINT ck_career_sites_display_name CHECK (display_name = BTRIM(display_name) AND display_name <> ''),
  CONSTRAINT ck_career_sites_interval CHECK (
    successful_interval_seconds > 0 AND successful_interval_seconds <= 31536000
  )
);

CREATE TABLE job_postings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  career_site_id BIGINT NOT NULL REFERENCES career_sites(id) ON DELETE CASCADE,
  external_key TEXT NOT NULL,
  title TEXT NOT NULL,
  description_text TEXT NOT NULL,
  canonical_url TEXT NOT NULL,
  employment_hint TEXT,
  location_hint TEXT,
  remote_hint TEXT,
  source_updated_at TIMESTAMPTZ,
  content_hash CHAR(64) NOT NULL,
  status TEXT NOT NULL,
  consecutive_misses INTEGER NOT NULL DEFAULT 0,
  first_seen_at TIMESTAMPTZ NOT NULL,
  last_seen_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  closed_at TIMESTAMPTZ,
  CONSTRAINT uq_job_postings_site_external_key UNIQUE (career_site_id, external_key),
  CONSTRAINT ck_job_postings_key CHECK (external_key = BTRIM(external_key) AND external_key <> ''),
  CONSTRAINT ck_job_postings_title CHECK (title <> ''),
  CONSTRAINT ck_job_postings_url_https CHECK (canonical_url LIKE 'https://%'),
  CONSTRAINT ck_job_postings_hash CHECK (content_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT ck_job_postings_status CHECK (status IN ('OPEN', 'CLOSED')),
  CONSTRAINT ck_job_postings_misses CHECK (consecutive_misses >= 0),
  CONSTRAINT ck_job_postings_times CHECK (
    last_seen_at >= first_seen_at AND updated_at >= first_seen_at
  ),
  CONSTRAINT ck_job_postings_closed CHECK (
    (status = 'OPEN' AND closed_at IS NULL) OR
    (status = 'CLOSED' AND closed_at IS NOT NULL)
  )
);

CREATE TABLE posting_skills (
  job_posting_id BIGINT NOT NULL REFERENCES job_postings(id) ON DELETE CASCADE,
  skill TEXT NOT NULL,
  PRIMARY KEY (job_posting_id, skill),
  CONSTRAINT ck_posting_skills_value CHECK (skill = BTRIM(skill) AND skill <> '')
);

CREATE TABLE crawl_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  career_site_id BIGINT NOT NULL REFERENCES career_sites(id) ON DELETE CASCADE,
  started_at TIMESTAMPTZ NOT NULL,
  finished_at TIMESTAMPTZ,
  outcome TEXT,
  failure_code TEXT,
  failure_message TEXT,
  fetched_count INTEGER NOT NULL DEFAULT 0,
  inserted_count INTEGER NOT NULL DEFAULT 0,
  updated_count INTEGER NOT NULL DEFAULT 0,
  touched_count INTEGER NOT NULL DEFAULT 0,
  missing_count INTEGER NOT NULL DEFAULT 0,
  closed_count INTEGER NOT NULL DEFAULT 0,
  reopened_count INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT ck_crawl_runs_outcome CHECK (outcome IS NULL OR outcome IN ('SUCCESS', 'FAILED')),
  CONSTRAINT ck_crawl_runs_completion CHECK (
    (finished_at IS NULL AND outcome IS NULL) OR
    (finished_at IS NOT NULL AND outcome IS NOT NULL)
  ),
  CONSTRAINT ck_crawl_runs_failure CHECK (
    (outcome = 'FAILED' AND failure_code IS NOT NULL AND failure_message IS NOT NULL) OR
    (outcome IS DISTINCT FROM 'FAILED' AND failure_code IS NULL AND failure_message IS NULL)
  ),
  CONSTRAINT ck_crawl_runs_counts CHECK (
    fetched_count >= 0 AND inserted_count >= 0 AND updated_count >= 0 AND
    touched_count >= 0 AND missing_count >= 0 AND closed_count >= 0 AND reopened_count >= 0
  )
);

CREATE TABLE crawl_leases (
  career_site_id BIGINT PRIMARY KEY REFERENCES career_sites(id) ON DELETE CASCADE,
  owner TEXT NOT NULL,
  acquired_at TIMESTAMPTZ NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT ck_crawl_leases_owner CHECK (owner = BTRIM(owner) AND owner <> ''),
  CONSTRAINT ck_crawl_leases_expiry CHECK (expires_at > acquired_at)
);

CREATE INDEX ix_job_postings_search_order ON job_postings (updated_at DESC, id DESC);
CREATE INDEX ix_job_postings_site_status ON job_postings (career_site_id, status);
CREATE INDEX ix_crawl_runs_site_finished ON crawl_runs (career_site_id, finished_at DESC, id DESC);
CREATE INDEX ix_crawl_leases_expiry ON crawl_leases (expires_at);
