/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as AccountSecurityRouteImport } from './routes/account/security'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as CompaniesSlugRouteImport } from './routes/companies/$slug'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as JobsIdRouteImport } from './routes/jobs/$id'
import { Route as SkillsSlugRouteImport } from './routes/skills/$slug'
import { Route as AdminSitesIndexRouteImport } from './routes/admin/sites/index'
import { Route as AdminSitesIdRouteImport } from './routes/admin/sites/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/account/security',
  path: '/account/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesSlugRoute = CompaniesSlugRouteImport.update({
  id: '/companies/$slug',
  path: '/companies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSlugRoute = SkillsSlugRouteImport.update({
  id: '/skills/$slug',
  path: '/skills/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSitesIndexRoute = AdminSitesIndexRouteImport.update({
  id: '/admin/sites/',
  path: '/admin/sites/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSitesIdRoute = AdminSitesIdRouteImport.update({
  id: '/admin/sites/$id',
  path: '/admin/sites/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/account/security': typeof AccountSecurityRoute
  '/admin/audit': typeof AdminAuditRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/admin/sites/$id': typeof AdminSitesIdRoute
  '/admin/sites/': typeof AdminSitesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/account/security': typeof AccountSecurityRoute
  '/admin/audit': typeof AdminAuditRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/admin/sites/$id': typeof AdminSitesIdRoute
  '/admin/sites': typeof AdminSitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/account/security': typeof AccountSecurityRoute
  '/admin/audit': typeof AdminAuditRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/admin/sites/$id': typeof AdminSitesIdRoute
  '/admin/sites/': typeof AdminSitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/login'
    | '/recover'
    | '/account/security'
    | '/admin/audit'
    | '/companies/$slug'
    | '/jobs/$id'
    | '/skills/$slug'
    | '/admin/'
    | '/jobs/'
    | '/admin/sites/$id'
    | '/admin/sites/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/login'
    | '/recover'
    | '/account/security'
    | '/admin/audit'
    | '/companies/$slug'
    | '/jobs/$id'
    | '/skills/$slug'
    | '/admin'
    | '/jobs'
    | '/admin/sites/$id'
    | '/admin/sites'
  id:
    | '__root__'
    | '/'
    | '/join'
    | '/login'
    | '/recover'
    | '/account/security'
    | '/admin/audit'
    | '/companies/$slug'
    | '/jobs/$id'
    | '/skills/$slug'
    | '/admin/'
    | '/jobs/'
    | '/admin/sites/$id'
    | '/admin/sites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  RecoverRoute: typeof RecoverRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AdminAuditRoute: typeof AdminAuditRoute
  CompaniesSlugRoute: typeof CompaniesSlugRoute
  JobsIdRoute: typeof JobsIdRoute
  SkillsSlugRoute: typeof SkillsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  AdminSitesIdRoute: typeof AdminSitesIdRoute
  AdminSitesIndexRoute: typeof AdminSitesIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/security': {
      id: '/account/security'
      path: '/account/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$slug': {
      id: '/companies/$slug'
      path: '/companies/$slug'
      fullPath: '/companies/$slug'
      preLoaderRoute: typeof CompaniesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$slug': {
      id: '/skills/$slug'
      path: '/skills/$slug'
      fullPath: '/skills/$slug'
      preLoaderRoute: typeof SkillsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sites/': {
      id: '/admin/sites/'
      path: '/admin/sites'
      fullPath: '/admin/sites/'
      preLoaderRoute: typeof AdminSitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sites/$id': {
      id: '/admin/sites/$id'
      path: '/admin/sites/$id'
      fullPath: '/admin/sites/$id'
      preLoaderRoute: typeof AdminSitesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  RecoverRoute: RecoverRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AdminAuditRoute: AdminAuditRoute,
  CompaniesSlugRoute: CompaniesSlugRoute,
  JobsIdRoute: JobsIdRoute,
  SkillsSlugRoute: SkillsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  AdminSitesIdRoute: AdminSitesIdRoute,
  AdminSitesIndexRoute: AdminSitesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
